name: ${{ github.event.inputs.workflow_name || 'CI Workflow' }}
on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Custom workflow name'
        required: false
        default: ''
        type: string
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          echo "Installing Dependencies....!"